;;; This file is automatically generated from file `literate-lisp.org'.
;;; Please read file `literate-lisp.org' to find out the usage and implementation detail of this source file.

(in-package #:literate-lisp)

(in-package :asdf)
(eval-when (:compile-toplevel :load-toplevel :execute)
  (export '(asdf::org) :asdf))
(defclass asdf::org (asdf:cl-source-file)
  ((asdf::type :initform "org")))

(defmethod asdf:perform :around (o (c asdf:org))
  (literate-lisp:with-literate-syntax
    (call-next-method)))

(defmethod asdf/system:find-system :around (name &optional (error-p t))
  (literate-lisp:with-literate-syntax
    (call-next-method)))

(in-package :literate-lisp)

